kind: pipeline
name: yadayada

steps:
- name: compile
  image: microsoft/aspnetcore-build
  commands:
  - sh build.sh
- name: build-image:
  image: microsoft/aspnetcore-build
  commands:
  - docker build -t dinorows/dotnetcore-container ./Web
